// Fylgja (https://fylgja.dev)
// Licensed under MIT Open Source

emodule.exports = {
  "xs": "420px",
  "xsMin": "(width >= 420px)",
  "xsMax": "(width < 420px)",
  "sm": "640px",
  "smMin": "(width >= 640px)",
  "smMax": "(width < 640px)",
  "md": "768px",
  "mdMin": "(width >= 768px)",
  "mdMax": "(width < 768px)",
  "lg": "1024px",
  "lgMin": "(width >= 1024px)",
  "lgMax": "(width < 1024px)",
  "xl": "1440px",
  "xlMin": "(width >= 1440px)",
  "xlMax": "(width < 1440px)",
  "xxl": "2200px",
  "xxlMin": "(width >= 2200px)",
  "xxlMax": "(width < 2200px)",
  "hdColor": "(dynamic-range: high)",
  "touch": "(hover: none) and (pointer: coarse)",
  "stylus": "(hover: none) and (pointer: fine)",
  "pointer": "(hover) and (pointer: coarse)",
  "mouse": "(hover) and (pointer: fine)",
  "schemeDark": "(prefers-color-scheme: dark)",
  "schemeLight": "(prefers-color-scheme: light)",
  "motionSafe": "(prefers-reduced-motion: no-preference)",
  "motionReduce": "(prefers-reduced-motion: reduce)",
  "opacitySafe": "(prefers-reduced-transparency: no-preference)",
  "opacityReduce": "(prefers-reduced-transparency: reduce)",
  "dataSafe": "(prefers-reduced-data: no-preference)",
  "dataReduce": "(prefers-reduced-data: reduce)",
  "contrastMore": "(prefers-contrast: more)",
  "contrastLess": "(prefers-contrast: less)",
  "portrait": "(orientation: portrait)",
  "landscape": "(orientation: landscape)"
};
